//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazeProjekatPokusaj2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompanyDbModelContainer : DbContext
    {
        public CompanyDbModelContainer()
            : base("name=CompanyDbModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Osoba> Osobas { get; set; }
        public virtual DbSet<Kompanija> Kompanije { get; set; }
        public virtual DbSet<Lokacija> Lokacije { get; set; }
        public virtual DbSet<Ugovor> Ugovori { get; set; }
        public virtual DbSet<UgovoreniProizvod> UgovoreniProizvodi { get; set; }
    }
}
