//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazeProjekatPokusaj2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kompanija
    {
        public int KID { get; set; }
        public string NazivKompanije { get; set; }
        public string GodinaOsnivanja { get; set; }
    
        public virtual Lokacija Lokacija { get; set; }
        public virtual Direktor Direktor { get; set; }
    }
}
