//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazeProjekatPokusaj2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokacija
    {
        public int LokID { get; set; }
        public int KompanijaKID { get; set; }
        public string Grad { get; set; }
        public string Ulica { get; set; }
        public string PostanskiBroj { get; set; }
    
        public virtual Kompanija Kompanija { get; set; }
    }
}
