//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazeProjekatPokusaj2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UgovoreniProizvod
    {
        public string OpisProizvoda { get; set; }
        public string VrednostProizvoda { get; set; }
        public int PRID { get; set; }
    
        public virtual Klijent Klijent { get; set; }
        public virtual Konsultant Konsultant { get; set; }
        public virtual Developer Developer { get; set; }
    }
}
