//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazeProjekatPokusaj2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni : Osoba
    {
        public string RadniStaz { get; set; }
        public int UgovorUID { get; set; }
    
        public virtual Ugovor Ugovor { get; set; }
    }
}
